### ISSUE TITLE
Laravel 5.7 

### ISSUE THREAD

**Issue by flick36** [DCzajkowski/auth-tests#9]
### Environment
- Laravel Version: 5.7.2
- PHP Version: 7.2.9

### Description:
Can we get a release for laravel 5.7 and test the new Email Verification thingy?

**Comment by DCzajkowski** [comment]
Absolutely! Currently I am away from home until Saturday, but after that I should have time to make those and make a release. 😉

**Comment by DCzajkowski** [comment]
It seems to be not as easy as I thought. Currently, e-mail verification is an optional thing — separate from the `make:auth` command. I am thinking of adding a flag, that would create a completely separate test file with just e-mail verification.

It would be available via flags:
- `make:auth-tests --with-email-verification` or `make:auth-tests -e` - (for new and existing projects) scaffold tests including e-mail verification test,
- `make:auth-tests --only-email-verification` - (for existing projects) scaffold only the e-mail verification test.

Another option would be to check if the `App\User` or `CustomNamespace\User` model implements the `MustVerifyEmail` interface. It could be as a separate feature that would be independent from the above flags.

**Comment by drbyte** [comment]
I say keep it simple.

IMO `make:auth-tests` should just create everything, but not overwrite existing test files by the same name. So that'll create any "missing" files (ie: catch-up existing projects)

And allow an optional `--force` or `--overwrite=true` (or whatever) to replace existing files by the same name, in case someone wants that.

Either way if someone wants to "not use" one of the scaffolded tests this package creates, they can just delete those files before committing them to VCS. 

This way there's no need to add a bunch of (maybe temporary) flags that will be rarely used.

Just my 2cents.

**Comment by flick36** [comment]
I support @drbyte suggestion, think of it as the preset command, it just deletes everything, and overwrites everything, and is up to the user to check and modify as needed.

**Comment by DCzajkowski** [comment]
Thank you for your feedback. There is already a `--force` option that overwrites without asking. Without it, the command prompt asks for each file if you want to overwrite it.

I don't like the option of having these tests created automatically without a flag, because it may cause many failing tests for people not using the feature. Unless we add a flag `--without-email-verification` that will not create this test and will be clearly shown in the README as a sensible default.

---

Do you guys think it's smart to add this test as a separate file (ie. as a separate feature), or is it better to put it in the `RegisterTest`, as it's really a sub-feature of the registration flow?

**Comment by drbyte** [comment]
I'd make it a separate test file, since it's an optional part of the registration flow. 
Several people won't use the email-verification feature, and if that were me I'd like to be able to just delete that file instead of having to hack the combined registration test file/s.

**Comment by DCzajkowski** [comment]
That's what I wanted to hear. 😅 Thanks! 💪

**Comment by DCzajkowski** [comment]
Shipped in [5.7](https://github.com/DCzajkowski/auth-tests/releases/tag/5.7.0) 🔥
